/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myThirdAttempt;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean check(ArrayList<Integer> arrayList, int e, int x)
    {
        System.out.println("inside search");
        if (arrayList == null) return false;
  
        for (int i = 0; i < arrayList.size(); i++){
            if (arrayList.get(i) == e && i != x)
                return false;
        }
        if (arrayList.get(x) == e)
            return true;
        return false;
    }
}
