/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myThirdAttempt;

import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;



class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test 
    public static void emptyArray() {
        App classUnderTest = new App();
        ArrayList<Integer> arrayList = new ArrayList<Integer>();
        assertFalse(classUnderTest.check(arrayList, 5, 4), "app should have a greeting");
    }
    @Test 
    public static void wrongPosition() {
        App classUnderTest = new App();
        ArrayList<Integer> arrayList = new ArrayList<Integer>();
        arrayList.add(1);
        arrayList.add(2);
        arrayList.add(3);
        arrayList.add(5);
        arrayList.add(4);
        assertFalse(classUnderTest.check(arrayList, 5, 4), "app should have a greeting");
    }
    @Test 
    public static void rigthPosition() {
        App classUnderTest = new App();
        ArrayList<Integer> arrayList = new ArrayList<Integer>();
        arrayList.add(1);
        arrayList.add(2);
        arrayList.add(3);
        arrayList.add(4);
        arrayList.add(5);
        assertTrue(classUnderTest.check(arrayList, 5, 4), "app should have a greeting");
    }
}
